### ISSUE TITLE
Left margin of pwa4wp-admin.css in several admin pages

### ISSUE THREAD

**Issue by s56bouya** [ryu-compin/pwa4wp#23]
Hi.

Plugin's CSS[pwa4wp-admin.css] is working on WordPress several admin pages.

Example : Customizer panel

![screenshot-admin-customizer-panel00](https://user-images.githubusercontent.com/15373114/49916345-ccae4280-fedd-11e8-84e8-e1835bf21d7c.png)

I think it is probably here.
https://github.com/ryu-compin/pwa4wp/blob/master/admin/css/pwa4wp-admin.css#L9

**Comment by ryu-compin** [comment]
Thank you for feedback Imamura san.
I'll add tags for all css class name and update next release soon.

**Comment by s56bouya** [comment]
Thanks!

**Comment by ryu-compin** [comment]
I fixed this issue, please try v1.1.4 update.
Thank you!
